# Generated by Django 6.1.1 on 2026-09-05 06:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326)),
                ('accessibility_score', models.FloatField(default=10.0, help_text='Accessibility index (0.0 to 10.0)')),
                ('connectivity_status', models.CharField(choices=[('normal', 'Normal'), ('degraded', 'Degraded'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('infra_type', models.CharField(choices=[('road', 'Road'), ('bridge', 'Bridge'), ('culvert', 'Culvert'), ('tunnel', 'Tunnel')], db_index=True, default='road', max_length=20)),
                ('road_classification', models.CharField(choices=[('national_highway', 'National Highway'), ('state_highway', 'State Highway'), ('major_district_road', 'Major District Road'), ('rural_road', 'Rural Road')], default='national_highway', max_length=30)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(geography=True, srid=4326)),
                ('start_node', models.CharField(db_index=True, max_length=100)),
                ('end_node', models.CharField(db_index=True, max_length=100)),
                ('length_km', models.FloatField(default=0.0)),
                ('base_speed_kmh', models.FloatField(default=50.0)),
                ('base_travel_time_min', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('accessible', 'Accessible'), ('risky', 'Risky'), ('blocked', 'Blocked')], db_index=True, default='accessible', max_length=20)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('moderate', 'Moderate'), ('poor', 'Poor'), ('damaged', 'Damaged')], default='good', max_length=20)),
                ('landslide_susceptibility', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('historical_landslide_count', models.PositiveIntegerField(default=0)),
                ('flood_hazard_zone', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('recent_rainfall_mm', models.FloatField(default=0.0)),
                ('weather_warning', models.BooleanField(default=False)),
                ('risk_score', models.FloatField(db_index=True, default=0.0, help_text='0 to 100 risk score')),
                ('disruption_probability', models.FloatField(default=0.0, help_text='0.0 to 1.0 probability')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='low', max_length=10)),
                ('top_factors', models.JSONField(blank=True, default=list)),
                ('last_assessed_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure', to='routes.district')),
            ],
            options={
                'verbose_name': 'Infrastructure Segment',
                'verbose_name_plural': 'Infrastructure Segments',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['district', 'status', 'risk_level'], name='routes_infr_distric_c7ac75_idx')],
            },
        ),
    ]
