# Generated by Django 6.1.1 on 2026-09-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='oneway',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='osm_segment_id',
            field=models.CharField(blank=True, help_text='Deterministic OSM identity: {way_id}-{min_node}-{max_node}-{key}', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='osm_way_id',
            field=models.BigIntegerField(blank=True, help_text='OSM way ID for source provenance', null=True),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='end_node',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='start_node',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
