# Generated by Django 6.1.1 on 2026-09-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_infrastructure_oneway_infrastructure_osm_segment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='landslide_nearby_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of historical landslide records within the configured proximity threshold.'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='landslide_nearest_distance_m',
            field=models.FloatField(blank=True, help_text='Distance in meters to nearest historical landslide record.', null=True),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='landslide_zone_member',
            field=models.BooleanField(default=False, help_text='Whether the Infrastructure geometry intersects a susceptibility zone.'),
        ),
    ]
