# Generated by Django 6.1.1 on 2026-09-07 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_infrastructure_landslide_enrichment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rainfall_mm', models.FloatField(default=0.0, help_text='Accumulated rainfall over recent window (e.g. past 24 hours) in mm')),
                ('condition', models.CharField(choices=[('clear', 'Clear'), ('moderate', 'Moderate'), ('heavy', 'Heavy'), ('extreme', 'Extreme')], default='clear', max_length=20)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('humidity_pct', models.FloatField(blank=True, null=True)),
                ('wind_speed_kmh', models.FloatField(blank=True, null=True)),
                ('weather_warning', models.BooleanField(default=False, help_text='Official weather warning status (False unless from an official warning source)')),
                ('warning_details', models.CharField(blank=True, default='', max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Raw provider response payload for audit and debugging')),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_snapshots', to='routes.district')),
            ],
            options={
                'verbose_name': 'Weather Snapshot',
                'verbose_name_plural': 'Weather Snapshots',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['district', '-recorded_at'], name='routes_weat_distric_b973c3_idx')],
            },
        ),
    ]
