# Generated by Django 6.1.1 on 2026-09-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_weathersnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='risk_updated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of latest calculated infrastructure risk', null=True),
        ),
    ]
