# Generated by Django 6.1.1 on 2026-09-05 08:05

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('vehicle_type', models.CharField(choices=[('truck', 'Heavy Truck'), ('van', 'Delivery Van'), ('emergency', 'Emergency / Relief Vehicle'), ('car', 'Light Vehicle / Car')], default='truck', max_length=20)),
                ('capacity_tons', models.FloatField(default=5.0)),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lng', models.FloatField(blank=True, null=True)),
                ('current_speed', models.FloatField(default=0.0, help_text='Speed in km/h')),
                ('last_ping_time', models.DateTimeField(blank=True, null=True)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['registration_number'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('origin', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('origin_name', models.CharField(max_length=255)),
                ('destination', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('destination_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('created', 'Created'), ('on_route', 'On Route'), ('delayed', 'Delayed'), ('at_risk', 'At Risk'), ('delivered', 'Delivered')], db_index=True, default='created', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('base_eta_minutes', models.FloatField(default=0.0)),
                ('predicted_eta_minutes', models.FloatField(default=0.0)),
                ('expected_delay_minutes', models.FloatField(default=0.0)),
                ('eta_factors', models.JSONField(blank=True, default=list)),
                ('last_eta_updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vehicle', 'status'], name='vehicles_tr_vehicle_6576dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('speed', models.FloatField(default=0.0, help_text='Speed in km/h')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vehicle', 'timestamp'], name='vehicles_lo_vehicle_07e53d_idx')],
            },
        ),
    ]
