# Generated by Django 6.1.1 on 2026-09-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationping',
            name='client_sync_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Client-generated UUID for offline sync deduplication.', null=True, unique=True),
        ),
    ]
