# Generated by Django 6.1.1 on 2026-09-05 05:37

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='reports/photos/%Y/%m/%d/')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('snapped_road_segment_id', models.IntegerField(blank=True, db_index=True, help_text='ID of the nearest RoadSegment (Phase 2 FK).', null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('incident_type', models.CharField(choices=[('flood', 'Flood'), ('landslide', 'Landslide'), ('road_damage', 'Road Damage'), ('obstruction', 'Obstruction')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=10)),
                ('client_timestamp', models.DateTimeField(help_text='Device timestamp from the mobile app.')),
                ('server_timestamp', models.DateTimeField(auto_now_add=True, help_text='Server receipt timestamp.')),
                ('ai_issue_type', models.CharField(blank=True, default='', max_length=20)),
                ('ai_severity', models.CharField(blank=True, default='', max_length=10)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('resolved', 'Resolved')], db_index=True, default='submitted', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incident_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident Report',
                'verbose_name_plural': 'Incident Reports',
                'ordering': ['-server_timestamp'],
            },
        ),
    ]
