# Generated by Django 6.1.1 on 2026-09-05 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='snapped_road_segment_id',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='snapped_infrastructure',
            field=models.ForeignKey(blank=True, help_text='Nearest Infrastructure segment snapped via PostGIS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reports', to='routes.infrastructure'),
        ),
    ]
