# Generated by Django 6.1.1 on 2026-09-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_incident_report_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='client_sync_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Client-generated UUID for offline sync deduplication (Last-Write-Wins).', null=True, unique=True),
        ),
    ]
